-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.6.0.83.4
-- Module  Version: 5.7
-- Wed Mar 30 17:16:33 2016

-- parameterized module component declaration
component CC_PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : CC_PLL
    port map (CLKI=>__, CLKOP=>__);
